-- SELECT PARA SABER O VALOR TOTAL COMPRADO POR UM CLIENTE ESPECIFICO
SELECT CLIENTE.NOME, 
   SUM(VENDA.VALOR_TOTAL) AS TOTAL_COMPRADO
  FROM VENDA 
 INNER JOIN CLIENTE
    ON VENDA.ID_CLIENTE = CLIENTE.ID
 WHERE VENDA.STATUS = 'CONCLUIDA'
 AND CLIENTE.NOME LIKE('%%') -- COLOQUE O NOME DO CLIENTE DESEJADO ENTRE OS SIMBOLOS %%
 GROUP BY CLIENTE.NOME;
