-- CRIANDO UMA VIEW QUE ARMAZENA AS PRINCIPAIS INFORMACOES DE CADA CLIENTE
CREATE VIEW v_informacoes_cliente as
SELECT C.ID,
 		C.NOME, 
        C.CPF,
		C.DATA_NASCIMENTO,
		STRING_AGG(CC.TIPO || ': ' || CC.VALOR, ' | ') AS CONTATOS,
		CE.LOGRADOURO,
		CE.NUMERO,
		CE.COMPLEMENTO,
		CE.BAIRRO,
		CE.CIDADE,
		CE.ESTADO,
		CE.CEP,
		CE.PAIS
   FROM CLIENTE C
  INNER JOIN CLIENTE_CONTATO CC
     ON C.ID = CC.ID_CLIENTE
  INNER JOIN CLIENTE_ENDERECO CE
     ON C.ID = CE.ID_CLIENTE
  GROUP BY C.ID,
           C.NOME,
		   C.CPF,
		   C.DATA_NASCIMENTO,
		   CE.LOGRADOURO,
		   CE.NUMERO,
		   CE.COMPLEMENTO,
		   CE.BAIRRO,
		   CE.CIDADE,
		   CE.ESTADO,
		   CE.CEP,
		   CE.PAIS;
		
		
		
