-- CRIANDO UMA VIEW QUE ARMAZENA AS PRINCIPAIS INFORMACOES DE CADA FUNCIONARIO
CREATE VIEW v_informacoes_funcionarios as
SELECT F.ID,
 	   F.NOME, 
       F.CPF,
	   F.DATA_NASCIMENTO,
	   F.DATA_ADMISSAO,
	   STRING_AGG(FC.TIPO || ': ' || FC.VALOR, ' | ') AS CONTATOS,
	   C.NOME AS CARGO,
	   F.SALARIO,
	   FE.LOGRADOURO,
	   FE.NUMERO,
	   FE.COMPLEMENTO,
	   FE.BAIRRO,
	   FE.CIDADE,
	   FE.ESTADO,
	   FE.CEP
  FROM FUNCIONARIOS F
  LEFT JOIN FUNCIONARIO_CONTATO FC
    ON F.ID = FC.ID_FUNCIONARIO
  LEFT JOIN CARGOS C  
    ON F.ID_CARGO = C.ID
  LEFT JOIN FUNCIONARIO_ENDERECO FE
    ON F.ID = FE.ID_FUNCIONARIO
 GROUP BY F.ID,
		  C.NOME,
		  FE.ID;
		
		