-- CRIANDO UMA VIEWS QUE MOSTRA PRODUTOS QUE ESTÃO COM O ESTOQUE NO LIMITE OU ABAIXO DO MINIMO PARA REPOSIÇÃO
CREATE VIEW V_QUANTIDADE_ABAIXO AS
SELECT P.NOME,
	   E.QUANTIDADE,
	   E.QUANTIDADE_MINIMA,
	   E.QUANTIDADE_MAXIMA
  FROM PRODUTOS P
 INNER JOIN ESTOQUE E
    ON P.ID = E.ID_PRODUTO
 WHERE E.QUANTIDADE <= E.QUANTIDADE_MINIMA;