-- CRIANDO UMA VIEW PARA VER AS COMPRAS EM ABERTO
CREATE VIEW V_VENDAS_EM_ABERTO AS
SELECT V.ID, 
       C.NOME AS NOME_CLIENTE,
	   C.CPF,
	   STRING_AGG(CC.TIPO || ': ' || CC.VALOR, ' | ') AS CONTATO_CLIENTE,
	   F.CRACHA AS CRACHA_VENDEDOR,
	   F.NOME AS VENDEDOR,
	   V.DATA_VENDA AS DATA_DA_VENDA,
	   V.STATUS,
	   P.STATUS AS STATUS_DO_PAGAMENTO,
	   FP.NOME AS FORMA_DE_PAGAMENTO,
	   P.VALOR_PAGO AS VALOR_TOTAL,
	   STRING_AGG(PR.NOME || ' (' || VI.QUANTIDADE || 'X)', ' | ' ) AS ITENS_DA_VENDA,
	   V.OBSERVACAO
  FROM VENDA V
  LEFT JOIN CLIENTE C
    ON V.ID_CLIENTE = C.ID
  LEFT JOIN CLIENTE_CONTATO CC
    ON C.ID = CC.ID_CLIENTE
  LEFT JOIN FUNCIONARIOS F
    ON F.ID = V.ID_FUNCIONARIO
  LEFT JOIN PAGAMENTO P 
    ON P.ID_VENDA = V.ID
  LEFT JOIN FORMA_PAGAMENTO FP
    ON FP.ID = P.ID_FORMA_PAGAMENTO
  LEFT JOIN VENDA_ITEM VI
    ON VI.ID_VENDA = V.ID
  LEFT JOIN PRODUTOS PR
    ON PR.ID = VI.ID_PRODUTO
 WHERE V.STATUS IN ('ABERTA', 'CANCELADA')
    OR P.STATUS = 'PENDENTE'
 GROUP BY V.ID, 
          C.NOME,
		  C.CPF,
		  F.CRACHA,
		  F.NOME,
		  V.DATA_VENDA,
		  V.STATUS,
		  P.STATUS,
		  FP.NOME,
		  P.VALOR_PAGO,
		  V.OBSERVACAO

	   