-- CRIANDO A VIEW V_PRODUTO_ESTOQUE PARA VER ONDE O PRODUTO ESTÁ ARMAZENADO E SUAS QUANTIDADES
CREATE VIEW V_PRODUTO_ESTOQUE AS
SELECT E.ID,
       P.NOME,
	   P.PRECO,
	   E.QUANTIDADE,
	   E.QUANTIDADE_MAXIMA,
	   E.QUANTIDADE_MINIMA,
	   LE.DESCRICAO AS LOCAL_DE_ARMAZENAMENTO
  FROM ESTOQUE E
 INNER JOIN PRODUTOS P
    ON E.ID_PRODUTO = P.ID
 INNER JOIN LOCAL_ESTOQUE LE
    ON E.ID_LOCAL = LE.ID;