-- SELECT PARA VER O VALOR TOTAL COMPRADO POR CLIENTE
SELECT CLIENTE.NOME, 
   SUM(VENDA.VALOR_TOTAL) AS TOTAL_COMPRADO
  FROM VENDA 
 INNER JOIN CLIENTE
    ON VENDA.ID_CLIENTE = CLIENTE.ID
 WHERE VENDA.STATUS = 'CONCLUIDA'
 GROUP BY CLIENTE.NOME
 ORDER BY TOTAL_COMPRADO DESC;
 

 

