-- CRIANDO A TABELA DE CLIENTES
CREATE TABLE CLIENTE (
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR(255) NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    DATA_NASCIMENTO DATE
);

-- DEFININDO ID COMO PK
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY(ID);