-- CRIANDO A TABELA QUE ARMAZENA O CONTATO DO CLIENTE
CREATE TABLE CLIENTE_CONTATO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_CLIENTE INTEGER NOT NULL,
    TIPO VARCHAR(50) NOT NULL CHECK(TIPO IN ('EMAIL', 'TELEFONE', 'WHATSAPP')),
    VALOR VARCHAR(100) NOT NULL
);

-- DEFININDO O ID COMO A PK DA TABELA 
ALTER TABLE CLIENTE_CONTATO ADD CONSTRAINT PK_CLIENTE_CONTATO
PRIMARY KEY(ID);

-- IDENTIFICANDO A FK QUE REFERENCIA O ID DO CLIENTE
ALTER TABLE CLIENTE_CONTATO ADD CONSTRAINT FK_CLIENTE_CONTATO_CLIENTE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
ON DELETE RESTRICT;