-- CRIANDO A TABELA QUE ARMAZENA O ENDERECO DO CLIENTE
CREATE TABLE CLIENTE_ENDERECO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_CLIENTE INTEGER NOT NULL,
    LOGRADOURO VARCHAR(200) NOT NULL,
    NUMERO VARCHAR(50) NOT NULL,
    COMPLEMENTO VARCHAR(255),
    BAIRRO VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    PAIS VARCHAR(100) NOT NULL
);

-- DEFININDO O ID COMO A PK DA TABELA
ALTER TABLE CLIENTE_ENDERECO ADD CONSTRAINT PK_CLIENTE_ENDERECO
PRIMARY KEY(ID);

-- DEFININDO O ID_CLIENTE COMO FK E REFERENCIADO O ID DA TABELA CLIENTE
ALTER TABLE CLIENTE_ENDERECO ADD CONSTRAINT FK_CLIENTE_ENDERECO_CLIENTE
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID)
ON DELETE RESTRICT;