-- CRIANDO A TABELA DE CARGOS DOS CLIENTES 
CREATE TABLE CARGOS(
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR(100) UNIQUE NOT NULL
);

-- DEFININDO O ID COMO PK
ALTER TABLE CARGOS ADD CONSTRAINT PK_CARGOS
PRIMARY KEY(ID);