-- CRIANDO A TABELA QUE ARMAZENA O CONTATO DO FORNECEDOR
CREATE TABLE FORNECEDOR_CONTATO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_FORNECEDOR_UNIDADE INTEGER NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    CARGO VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL
);

-- DEFININDO O ID COMO PK DA TABELA
ALTER TABLE FORNECEDOR_CONTATO ADD CONSTRAINT PK_FORNECEDOR_CONTATO
PRIMARY KEY(ID);

-- IDENTIFICANDO O ID_FORNECEDOR_UNIDADE COMO FK E REFERENCIANDO O ID DA TABELA FORNECEDOR_UNDADE
ALTER TABLE FORNECEDOR_CONTATO ADD CONSTRAINT FK_FORNECEDOR_CONTATO_UNIDADE
FOREIGN KEY(ID_FORNECEDOR_UNIDADE) REFERENCES FORNECEDOR_UNIDADE(ID)
ON DELETE RESTRICT;