-- CRIANDO A TABELA QUE ARMAZENA OS PRODUTOS
CREATE TABLE PRODUTOS(
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR(255) NOT NULL,
    PRECO NUMERIC(10,2) NOT NULL,
    ID_CATEGORIA INTEGER NOT NULL,
    ID_FORNECEDOR_UNIDADE INTEGER NOT NULL,
    ATIVO CHAR(1) NOT NULL CHECK (ATIVO IN('A', 'I'))
);

-- DEFININDO ID COMO PK
ALTER TABLE PRODUTOS ADD CONSTRAINT PK_PRODUTOS
PRIMARY KEY(ID);

-- IDENTIFICANDO ID_CATEGORIA COMO FK E REFERENCIANDO O ID DA TABELA CATEGORIA
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTO_CATEGORIA
FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID)
ON DELETE RESTRICT;

-- IDENTIFICANDO ID_FORNECEDOR_UNIDADE COMO FK E REFERENCIANDO O ID DA TABELA FORNECEDOR_UNIDADE
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTO_FORNECEDOR_UNIDADE
FOREIGN KEY(ID_FORNECEDOR_UNIDADE) REFERENCES FORNECEDOR_UNIDADE(ID)
ON DELETE RESTRICT;