-- CRIANDO A TABELA DE DE LOCAL ESTOQUE
CREATE TABLE LOCAL_ESTOQUE(
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    DESCRICAO VARCHAR(255) NOT NULL
);

-- IDENTIFICANDO O ID COMO PK DA TABELA
ALTER TABLE LOCAL_ESTOQUE ADD CONSTRAINT PK_LOCAL_ESTOQUE
PRIMARY KEY(ID);