-- CRIANDO A TABELA QUE GUARDA O TIPO DE MOVIMENTO DO ESTOQUE
CREATE TABLE TIPO_MOVIMENTO_ESTOQUE(
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    MOVIMENTO VARCHAR(50) NOT NULL
);

-- IDENTIFICANDO O ID COMO PK
ALTER TABLE TIPO_MOVIMENTO_ESTOQUE ADD CONSTRAINT PK_TIPO_MOVIMENTO_ESTOQUE
PRIMARY KEY(ID);
