-- CRIANDO A TABELA QUE GUARDA OS MOVIMENTOS DE ESTOQUE
CREATE TABLE MOVIMENTO_ESTOQUE(
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_PRODUTO INTEGER NOT NULL,
    ID_VENDA_ITEM INTEGER,
    ID_TIPO_MOVIMENTO INTEGER NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    DATA_MOVIMENTO TIMESTAMPTZ DEFAULT NOW(),
    OBSERVACAO VARCHAR(200)
);

-- IDENTIFICANDO O ID COMO PK
ALTER TABLE MOVIMENTO_ESTOQUE ADD CONSTRAINT PK_MOVIMENTO_ESTOQUE
PRIMARY KEY(ID);

-- REFERENCIANDO O ID DO PRODUTO NA FK_MOVIMENTO_ESTOQUE_PRODUTO
ALTER TABLE MOVIMENTO_ESTOQUE ADD CONSTRAINT FK_MOVIMENTO_ESTOQUE_PRODUTO
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS(ID)
ON DELETE RESTRICT;

-- REFERENCIANDO O ID DA VENDA ITEM NA FK_VENDA_ITEM_MOVIMENTO_ESTOQUE
ALTER TABLE MOVIMENTO_ESTOQUE ADD CONSTRAINT FK_VENDA_ITEM_MOVIMENTO_ESTOQUE
FOREIGN KEY(ID_VENDA_ITEM) REFERENCES VENDA_ITEM(ID)
ON DELETE RESTRICT;

-- REFERENCIANDO O ID DO TIPO DE MOVIMENTO NA FK_MOVIMENTO_ESTOQUE_TIPO_MOVIMENTO
ALTER TABLE MOVIMENTO_ESTOQUE ADD CONSTRAINT FK_MOVIMENTO_ESTOQUE_TIPO_MOVIMENTO
FOREIGN KEY(ID_TIPO_MOVIMENTO) REFERENCES TIPO_MOVIMENTO_ESTOQUE(ID)
ON DELETE RESTRICT;