-- CRIANDO A TABELA DE FUNCIONARIOS
CREATE TABLE FUNCIONARIOS(
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    CRACHA VARCHAR(30) UNIQUE NOT NULL,
    NOME VARCHAR(200) NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    DATA_ADMISSAO DATE NOT NULL,
    ID_CARGO INTEGER NOT NULL,
    SALARIO NUMERIC(10,2) NOT NULL
);

-- DEFININDO ID COMO PRIMARY KEY
ALTER TABLE FUNCIONARIOS ADD CONSTRAINT PK_FUNCIONARIO
PRIMARY KEY(ID);

-- IDENTIFICANDO O ID_CARGO COMO FK QUE REFERENCIA O ID DA TABELA CARGO
ALTER TABLE FUNCIONARIOS ADD CONSTRAINT FK_FUNCIONARIO_CARGO
FOREIGN KEY(ID_CARGO) REFERENCES CARGOS(ID)
ON DELETE RESTRICT;

