-- CRIANDO A TABELA FUNCIONARIO_CONTATO
CREATE TABLE FUNCIONARIO_CONTATO(
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_FUNCIONARIO INTEGER NOT NULL,
    NUMERO VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
);

-- DEFININDO A PK DA TABELA FUNCIONARIO_CONTATO
ALTER TABLE FUNCIONARIO_CONTATO ADD CONSTRAINT PK_FUNCIONARIO_CONTATO
PRIMARY KEY(ID);

-- IDENTIFICANDO A FK DA TABELA FUNCIONARIO_CONTATO QUE REFERENCIA O CAMPO ID DA TABELA FUNCIONARIO
ALTER TABLE FUNCIONARIO_CONTATO ADD CONSTRAINT FK_FUNCIONARIO_CONTATO_FUNCIONARIO
FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID)
ON DELETE RESTRICT;

