-- CRIANDO A TABELA QUE ARMAZENA O ENDERECO DO FUNCIONARIO
CREATE TABLE FUNCIONARIO_ENDERECO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_FUNCIONARIO INTEGER NOT NULL,
    LOGRADOURO VARCHAR(200) NOT NULL,
    NUMERO VARCHAR(50) NOT NULL,
    COMPLEMENTO VARCHAR(255) NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CEP VARCHAR(10) NOT NULL
);

-- DEFININDO O ID COMO A PK DA TABELA
ALTER TABLE FUNCIONARIO_ENDERECO ADD CONSTRAINT PK_FUNCIONARIO_ENDERECO
PRIMARY KEY(ID);

-- DEFININDO O ID_FUNCIONARIO COMO FK E REFERENCIADO O ID DA TABELA FUNCIONARIO
ALTER TABLE FUNCIONARIO_ENDERECO ADD CONSTRAINT FK_FUNCIONARIO_ENDERECO_FUNCIONARIO
FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID)
ON DELETE RESTRICT;