-- CRIANDO A TABELA DE CATEGORIAS DE PRODUTOS
CREATE TABLE CATEGORIA (
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255),
    ATIVO CHAR(1) NOT NULL CHECK(ATIVO IN ('A', 'I'))
);

-- DEFININDO O ID COMO PK
ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA
PRIMARY KEY(ID);