-- CRIANDO A TABELA QUE ARMAZENA O ID E O NOME FANTASIA DO FORNECEDOR
CREATE TABLE FORNECEDOR(
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    NOME_FANTASIA VARCHAR(255) NOT NULL
);

-- DEFININDO O ID COMO PK DA TABELA
ALTER TABLE FORNECEDOR ADD CONSTRAINT PK_FORNECEDOR
PRIMARY KEY(ID);