-- CRIANDO A TABELA QUE ARMAZENA INFORMAÇÕES DA UNIDADES DE CADA FORNECEDOR
CREATE TABLE FORNECEDOR_UNIDADE (
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_EMPRESA INTEGER NOT NULL,
    CNPJ VARCHAR(18) NOT NULL UNIQUE,
    RAZAO_SOCIAL VARCHAR(255) NOT NULL,
    INSCRICAO_ESTADUAL VARCHAR(20) NOT NULL,
    DESC_UNIDADE VARCHAR(255) NOT NULL,
    ATIVO CHAR(1) NOT NULL CHECK (ATIVO IN ('A', 'I'))
);

-- DEFININDO O ID COMO PK
ALTER TABLE FORNECEDOR_UNIDADE ADD CONSTRAINT PK_FORNECEDOR_UNIDADE
PRIMARY KEY(ID);

-- IDENTIFICANDO O ID_EMPRESA COMO FK E REFERENCIANDO O ID DA TABELA FORNECEDOR
ALTER TABLE FORNECEDOR_UNIDADE ADD CONSTRAINT FK_FORNECEDOR_UNIDADE_EMPRESA
FOREIGN KEY(ID_EMPRESA) REFERENCES FORNECEDOR(ID)
ON DELETE RESTRICT;