-- CRIANDO A TABELA QUE ARMAZENA O ENDERECO DO FORNECEDOR
CREATE TABLE FORNECEDOR_ENDERECO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_FORNECEDOR_UNIDADE INTEGER NOT NULL,
    TIPO_ENDERECO VARCHAR(255) NOT NULL,
    LOGRADOURO VARCHAR(255) NOT NULL,
    NUMERO VARCHAR(255) NOT NULL,
    COMPLEMENTO VARCHAR(255),
    BAIRRO VARCHAR(200) NOT NULL,
    CIDADE VARCHAR(200) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CEP VARCHAR(10) NOT NULL
);

-- DEFININDO ID COMO PK DA TABELA 
ALTER TABLE FORNECEDOR_ENDERECO ADD CONSTRAINT PK_FORNECEDOR_ENDERECO
PRIMARY KEY(ID);

-- IDENTIFICANDO ID_FORNECEDOR_UNIDADE COMO FK E REFERENCIADO O ID DA TABELA FORNECEDOR_UNIDADE
ALTER TABLE FORNECEDOR_ENDERECO ADD CONSTRAINT FK_FORNECEDOR_UNIDADE_ENDERECO
FOREIGN KEY(ID_FORNECEDOR_UNIDADE) REFERENCES FORNECEDOR_UNIDADE(ID)
ON DELETE RESTRICT;