-- CRIANDO A TABELA DE ESTOQUE
CREATE TABLE ESTOQUE(
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_PRODUTO INTEGER NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    QUANTIDADE_MAXIMA INTEGER NOT NULL,
    QUANTIDADE_MINIMA INTEGER NOT NULL,
    ID_LOCAL INTEGER NOT NULL,
    DATA_ATUALIZACAO DATE
);

-- IDENTIFICANDO O ID COMO PK
ALTER TABLE ESTOQUE ADD CONSTRAINT PK_ESTOQUE
PRIMARY KEY(ID);

-- REFERENCIANDO O ID DO PRODUTO DENTRO DA TABELA ESTOQUE
ALTER TABLE ESTOQUE ADD CONSTRAINT FK_PRODUTO_ESTOQUE
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS(ID)
ON DELETE RESTRICT;

-- REFERENCIANDO O ID DO LOCAL DENTRO DA TABELA ESTOQUE
ALTER TABLE ESTOQUE ADD CONSTRAINT FK_LOCAL_ESTOQUE
FOREIGN KEY(ID_LOCAL) REFERENCES LOCAL_ESTOQUE(ID)
ON DELETE RESTRICT;

