-- CRIANDO A TABELA COM AS FORMAS DE PAGAMENTO
CREATE TABLE FORMA_PAGAMENTO(
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR(40) NOT NULL
);

-- IDENTIFICANDO O ID COMO PK DA TABELA
ALTER TABLE FORMA_PAGAMENTO ADD CONSTRAINT PK_FORMA_PAGAMENTO
PRIMARY KEY(ID);