-- CRIANDO A TABELA QUE ARMAZENA AS INFORMACOES DAS VENDAS
CREATE TABLE VENDA(
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_CLIENTE INTEGER NOT NULL,
    ID_FUNCIONARIO INTEGER NOT NULL,
    DATA_VENDA DATE NOT NULL,
    STATUS VARCHAR(40) NOT NULL,
    VALOR_BRUTO NUMERIC(10,2) NOT NULL,
    VALOR_DESCONTO NUMERIC(10,2) NOT NULL,
    VALOR_TOTAL NUMERIC(10,2) NOT NULL
    OBSERVACAO VARCHAR
);

-- IDENTIFICANDO ID COMO PK
ALTER TABLE VENDA ADD CONSTRAINT PK_VENDA
PRIMARY KEY(ID);

-- REFERENCIADO O ID DO CLIENTE NA FK_CLIENTE_VENDA
ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_CLIENTE
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID)
ON DELETE RESTRICT;

-- REFERENCIANDO O ID DO FUNCIONARIO NA FK_VENDA_FUNCIONARIO
ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_FUNCIONARIO
FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID)
ON DELETE RESTRICT;