-- CRIANDO AS TABELAS QUE ARMAZENA OS PAGAMENTOS
CREATE TABLE PAGAMENTO(
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_VENDA INTEGER NOT NULL,
    ID_FORMA_PAGAMENTO INTEGER NOT NULL,
    VALOR_PAGO NUMERIC(10,2) NOT NULL,
    STATUS VARCHAR(40) NOT NULL,
    DATA_PAGAMENTO DATE NOT NULL
);

-- IDENTIFICANDO O ID COMO PK DA TABELA
ALTER TABLE PAGAMENTO ADD CONSTRAINT PK_PAGAMENTO
PRIMARY KEY(ID);

-- REFERENCIANDO O ID DA TABELA VENDA NA FK_PAGAMENTO_VENDA
ALTER TABLE PAGAMENTO ADD CONSTRAINT FK_PAGAMENTO_VENDA
FOREIGN KEY(ID_VENDA) REFERENCES VENDA(ID)
ON DELETE RESTRICT;

-- REFERENCIANDO O ID DA TABELA FORMA_PAGAMENTO NA FK_PAGAMENTO_FORMA_PAGAMENTO
ALTER TABLE PAGAMENTO ADD CONSTRAINT FK_PAGAMENTO_FORMA_PAGAMENTO
FOREIGN KEY(ID_FORMA_PAGAMENTO) REFERENCES FORMA_PAGAMENTO(ID)
ON DELETE RESTRICT;
