-- CRIANDO A TABELA QUE GUARDA OS ITENS DE UMA VENDA
CREATE TABLE VENDA_ITEM(
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_VENDA INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    PRECO_UNITARIO NUMERIC(10,2) NOT NULL,
    VALOR_DESCONTO NUMERIC(10,2) NOT NULL,
    SUBTOTAL NUMERIC(10,2) NOT NULL 
);

-- IDENTIFICANDO O ID COMO PK
ALTER TABLE VENDA_ITEM ADD CONSTRAINT PK_VENDA_ITEM
PRIMARY KEY(ID);

-- REFERENCIANDO O ID DA TABELA VENDA NA FK_VENDA_ITEM_VENDA
ALTER TABLE VENDA_ITEM ADD CONSTRAINT FK_VENDA_ITEM_VENDA
FOREIGN KEY(ID_VENDA) REFERENCES VENDA(ID)
ON DELETE RESTRICT;

-- REFERENCIANDO O ID DO PRODUTO NA FK_VENDA_ITEM_PRODUTO
ALTER TABLE VENDA_ITEM ADD CONSTRAINT FK_VENDA_ITEM_PRODUTO
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID)
ON DELETE RESTRICT;
